### PR TITLE
Add WEBMIDI.js library information

### PR DESCRIPTION
**Pull request by djipco**

### CODE REVIEW

**Comment by davepagurek** [comment]
Hi @djipco, thanks for your submission! Would you mind using a 1500x1000 image for your preview? that will be the aspect ratio we use on the site - with anything else, some of your text might get cropped out.

**Comment by djipco** [comment]
I looked too fast, I thought you needed a square ratio. Sorry. I'll fix it as soon as I'm back at my computer.

**Comment by davepagurek** [comment]
No problem, thanks!

**Comment by djipco** [comment]
I uploaded an image with the correct size.

**Review by davepagurek — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
